# Generated by Django 5.1.1 on 2024-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.FloatField(default=0, help_text='In minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(default=''),
        ),
    ]
