# Generated by Django 5.1.1 on 2024-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='recipe_pics'),
        ),
    ]
